# Generated by Django 5.0.3 on 2024-03-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userdetails_remove_exercises_calories_burnt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdaily',
            name='calories',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userdaily',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
