# Generated by Django 5.0.3 on 2024-03-26 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_userdaily_calories_alter_userdaily_weight_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exercises',
        ),
    ]
