# Generated by Django 5.0.3 on 2024-06-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_exercises'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdaily',
            name='sleep',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='dob',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
