# Generated by Django 5.0.3 on 2024-06-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userdaily_sleep_userdetails_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdaily',
            name='date',
            field=models.DateField(auto_now_add=True, unique=True),
        ),
    ]
