# Generated by Django 5.0.3 on 2024-06-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_userdaily_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdaily',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='userdaily',
            unique_together={('user', 'date')},
        ),
    ]
