# Generated by Django 5.0.3 on 2024-06-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_userdaily_date_alter_userdaily_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='dob',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
