# Generated by Django 5.0.3 on 2024-03-30 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreDefinedWorkoutNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PreDefinedWorkouts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.IntegerField(null=True)),
                ('time', models.IntegerField(null=True)),
                ('order', models.IntegerField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.exercises')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.predefinedworkoutnames')),
            ],
        ),
    ]
