# Generated by Django 5.0.3 on 2024-03-31 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_predefinedworkoutnames_predefinedworkouts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predefinedworkoutnames',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
