# Generated by Django 5.0.3 on 2024-04-02 15:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_alter_predefinedworkoutnames_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predefinedworkouts',
            name='order',
        ),
        migrations.AddField(
            model_name='predefinedworkouts',
            name='added_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
