# Generated by Django 5.0.3 on 2024-04-06 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0006_rename_userid_customworkoutnames_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customworkouts',
            old_name='workoutid',
            new_name='workout',
        ),
    ]
