# Generated by Django 5.0.3 on 2024-06-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0007_rename_workoutid_customworkouts_workout'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercises',
            name='met',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
    ]
